data_source:
  base_url: https://www.ncei.noaa.gov/data/local-climatological-data/access/
  year: 2022
  output: C:/Users/91989/Downloads/BDL_assgn4-main/BDL_assgn4-main/Climate_dataset{year}.html
  local: C:/Users/91989/Downloads/BDL_assgn4-main/BDL_assgn4-main/
  max_files: 10
  temp_dir: C:/Users/91989/Downloads/BDL_assgn4-main/BDL_assgn4-main/data
data_process:
  dest_folder: C:/Users/91989/Downloads/BDL_assgn4-main/BDL_assgn4-main/process_data
data_prepare:
  dest_folder: C:/Users/91989/Downloads/BDL_assgn4-main/BDL_assgn4-main/prepare_data
evaluate:
  output: C:/Users/91989/Downloads/BDL_assgn4-main/BDL_assgn4-main/output
